import { useEffect, useRef, useState } from "react";
import { FiDownload, FiUpload } from "react-icons/fi";
import { useAuth } from "../../../contexts/AuthContext.jsx";
import { useAppSettings } from "../../../hooks/useAppSettings.js";
import { useHierarchyImport } from "../../../hooks/useHierarchyImport.js";
import {
  buildTreeFromCsvRows,
  buildTreeFromManualItems,
  countNodes,
  csvRowsToObjects,
  findFirstConfigSource,
  looksLikeCsv,
  parseCsv
} from "../../../utils/hierarchyImport.js";
import { csvCell } from "../../../utils/workbench/formatters.js";
import { dateStamp, downloadCsv } from "../../../utils/csvExport.js";
import { Button, EmptyState, InfoTooltip, Kpi, TextField, TypeBadge, WorkbenchHeader, typeIconSrc } from "../ui/WorkbenchPrimitives.jsx";
import { CreateWorkItemWizard } from "./CreateWorkItemWizard.jsx";

const manualTypeOptions = ["Epic", "Feature", "User Story", "Task", "Test Case", "Bug"];

const workItemAllowedChildren = {
  Epic: ["Feature", "User Story", "Task", "Test Case", "Bug"],
  Feature: ["User Story", "Task", "Test Case", "Bug"],
  "User Story": ["Task", "Test Case"],
  Task: ["Test Case"],
  "Test Case": [],
  Bug: []
};

function validateTree(root) {
  const errors = {};
  function addError(nodeId, message) {
    if (!nodeId) return;
    errors[nodeId] = [...(errors[nodeId] || []), message];
  }

  function walk(node) {
    const children = node.children || [];
    children.forEach((child) => {
      if (node.type !== "root") {
        const allowed = workItemAllowedChildren[node.type] || [];
        if (!allowed.includes(child.type)) {
          addError(node.id, `Tipo ${node.type} não pode ter filho ${child.type}.`);
          addError(child.id, `Tipo ${child.type} não pode ser filho de ${node.type}.`);
        }
      }
      if (child.children?.length > 0 && (workItemAllowedChildren[child.type] || []).length === 0) {
        addError(child.id, `Tipo ${child.type} não pode ter filhos.`);
      }
      walk(child);
    });
  }

  walk(root);
  return errors;
}

function buildDefaultQaCsv(defaults = {}) {
  const area = defaults.areaPath || "WebApp\\MB Labs";
  const iteration = defaults.iterationPath || "WebApp\\MB Labs\\May [2026] MB Labs";
  const tags = defaults.tags || "automation;qa";
  const rows = [
    ["ID", "Work Item Type", "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Area Path", "Iteration Path", "Country", "Tags", "Description"],
    ["", "Epic", "QA Automation", "", "", "", "", area, iteration, "All", tags, "Automation backlog generated by Stark Hub."],
    ["", "Feature", "", "Checkout", "", "", "", area, iteration, "All", tags, "Checkout quality coverage."],
    ["", "User Story", "", "", "[Last Minute] Automation for checkout journey.", "", "", area, iteration, "All", tags, "Checkout journey."],
    ["", "Task", "", "", "", "[Last Minute] Main Flow", "", area, iteration, "All", tags, "Main flow scenarios."],
    ["", "Test Case", "", "", "", "", "[LT] Checkout displays Last Minute component", area, iteration, "All", tags, "**Steps:**\n1. Select movie and seat.\n2. Continue to Checkout.\n\n**Expected Result:** Component is displayed above payment options."]
  ];
  return rows.map((row) => row.map(csvCell).join(",")).join("\n");
}

function buildDefaultManualItems(defaults = {}) {
  const area = defaults.areaPath || "WebApp\\MB Labs";
  const iteration = defaults.iterationPath || "WebApp\\MB Labs\\May [2026] MB Labs";
  const tags = defaults.tags || "automation;qa";
  const common = { areaPath: area, iterationPath: iteration, countryValue: "All", tags };
  const epic = { id: "manual-epic", parentId: null, type: "Epic", title: "QA Automation", ...common, description: "Automation backlog generated by Stark Hub." };
  const feature = { id: "manual-feature", parentId: epic.id, type: "Feature", title: "Checkout", ...common, description: "Checkout quality coverage." };
  const story = { id: "manual-story", parentId: feature.id, type: "User Story", title: "[Last Minute] Automation for checkout journey.", ...common, description: "Checkout journey." };
  const task = { id: "manual-task", parentId: story.id, type: "Task", title: "[Last Minute] Main Flow", ...common, description: "Main flow scenarios." };
  const testCase = { id: "manual-test", parentId: task.id, type: "Test Case", title: "[LT] Checkout displays Last Minute component", ...common, description: "**Steps:**\n1. Select movie and seat.\n2. Continue to Checkout.\n\n**Expected Result:** Component is displayed above payment options." };
  return [epic, feature, story, task, testCase];
}

function flattenWithDepth(items) {
  const byParent = new Map();
  items.forEach((item) => {
    const key = item.parentId || "root";
    if (!byParent.has(key)) byParent.set(key, []);
    byParent.get(key).push(item);
  });
  const result = [];
  (function walk(parentKey, depth) {
    (byParent.get(parentKey) || []).forEach((item) => {
      result.push({ ...item, depth });
      walk(item.id, depth + 1);
    });
  })("root", 0);
  return result;
}

function cloneTree(node) {
  return {
    ...node,
    children: (node.children || []).map(cloneTree)
  };
}

function findNodeById(node, id) {
  if (!node || !id) return null;
  if (node.id === id) return node;
  for (const child of node.children || []) {
    const found = findNodeById(child, id);
    if (found) return found;
  }
  return null;
}

function flattenTree(node, depth = 0, rows = []) {
  if (!node) return rows;
  rows.push({ ...node, depth });
  (node.children || []).forEach((child) => flattenTree(child, depth + 1, rows));
  return rows;
}

function normalizeTag(value) {
  return String(value || "").trim().replace(/^,+|,+$/g, "");
}

function TagInput({ tags, value, onChange, onAdd, onRemove, placeholder }) {
  return (
    <div className="mbwi-tag-input">
      <div className="mbwi-tag-row">
        {tags.map((tag) => (
          <span key={tag} className="mbwi-tag-pill">
            {tag}
            <button type="button" onClick={() => onRemove(tag)} aria-label={`Remover tag ${tag}`}><i className="bi bi-x" /></button>
          </span>
        ))}
        <input
          className="mbwi-tag-input-field"
          value={value}
          onChange={(event) => onChange(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter") {
              event.preventDefault();
              const next = normalizeTag(value);
              if (next) onAdd(next);
            }
          }}
          placeholder={placeholder}
        />
      </div>
    </div>
  );
}

function removeNodeById(node, nodeId) {
  let removed = null;
  const children = [];
  for (const child of node.children || []) {
    if (child.id === nodeId) {
      removed = child;
      continue;
    }
    const [nextChild, childRemoved] = removeNodeById(child, nodeId);
    if (childRemoved) removed = childRemoved;
    children.push(nextChild);
  }
  return [{ ...node, children }, removed];
}

function countDescendants(node) {
  return (node.children || []).reduce((count, child) => count + 1 + countDescendants(child), 0);
}

function collectAllNodeIds(node, collector = []) {
  if (node.type !== "root" && node.id) collector.push(node.id);
  for (const child of node.children || []) collectAllNodeIds(child, collector);
  return collector;
}

function assignTreeIds(root) {
  let counter = 1;
  function walk(node) {
    if (node.type !== "root") node.id = node.id || `import-node-${counter++}`;
    for (const child of node.children || []) walk(child);
  }
  walk(root);
  return root;
}

function isAncestorOf(root, ancestorId, nodeId) {
  if (!ancestorId || !nodeId || ancestorId === nodeId) return false;
  const ancestor = findNodeById(root, ancestorId);
  return Boolean(ancestor && findNodeById(ancestor, nodeId));
}

function TreePreview({ node, depth = 0, draggingId, dropTargetId, onToggle, onMove, errors = {} }) {
  if (!node || node.type === "root") {
    return <>{(node?.children || []).map((child) => <TreePreview key={child.id} node={child} depth={0} draggingId={draggingId} dropTargetId={dropTargetId} onToggle={onToggle} onMove={onMove} />)}</>;
  }

  const hasChildren = (node.children || []).length > 0;
  const isExpanded = hasChildren ? onToggle?.isExpanded?.(node.id) : false;
  const childCount = node.children?.length || 0;
  const descendantCount = countDescendants(node);
  const isDropTarget = dropTargetId === node.id;

  const nodeErrors = errors[node.id] || [];
  return (
    <div className={`mbwi-tree-node${isDropTarget ? " drop-target" : ""}${draggingId === node.id ? " dragging" : ""}${nodeErrors.length ? " invalid" : ""}`}>
      <div
        className={`mbwi-node-row${nodeErrors.length ? " error" : ""}`}
        draggable
        onDragStart={(event) => {
          event.dataTransfer.setData("text/plain", node.id);
          event.dataTransfer.effectAllowed = "move";
          onToggle.setDragging(node.id);
        }}
        onDragEnd={() => onToggle.clearDrag()}
        onDragOver={(event) => {
          event.preventDefault();
          onToggle.setDropTarget(node.id);
        }}
        onDrop={(event) => {
          event.preventDefault();
          event.stopPropagation();
          const payload = event.dataTransfer.getData("text/plain") || "";
          if (payload.startsWith("new-type:")) {
            onToggle.onDropNewType?.(payload.replace("new-type:", ""), node.id);
            onToggle.clearDrag();
            return;
          }
          onMove(payload, node.id);
          onToggle.clearDrag();
        }}
        onDragLeave={() => onToggle.clearDropTarget()}
      >
        <button
          type="button"
          className={`mbwi-node-toggle${hasChildren ? "" : " empty"}`}
          onClick={(event) => {
            event.preventDefault();
            if (hasChildren) onToggle.toggle(node.id);
          }}
          aria-label={hasChildren ? (isExpanded ? "Recolher" : "Expandir") : "Sem filhos"}
        >
          {hasChildren ? (isExpanded ? "−" : "+") : ""}
        </button>
        {onToggle?.onEdit && (
          <button type="button" className="mbwi-edit-inside-badge" onClick={(event) => { event.preventDefault(); event.stopPropagation(); onToggle.onEdit(node.id); }} title="Editar item">
            <i className="bi bi-pencil" />
          </button>
        )}
        <div className="mbwi-node-title">
          <div className="mbwi-type-wrap">
            <TypeBadge type={node.type} />
          </div>
          <strong>{node.title || node.type}</strong>
        </div>
        <span className="mbwi-node-meta">
          {childCount > 0 ? `${childCount} filho${childCount === 1 ? "" : "s"} · ${descendantCount} nós` : "Sem filhos"}
        </span>
        
      </div>
      {nodeErrors.length > 0 && (
        <div className="mbwi-node-error">
          {nodeErrors.map((message, index) => <div key={index}>{message}</div>)}
        </div>
      )}
      {hasChildren && isExpanded && <div className="mbwi-node-children">{node.children.map((child) => <TreePreview key={child.id} node={child} depth={depth + 1} draggingId={draggingId} dropTargetId={dropTargetId} onToggle={onToggle} onMove={onMove} />)}</div>}
    </div>
  );
}

function ManualItemForm({ items, onAdd }) {
  const [type, setType] = useState("Epic");
  const [title, setTitle] = useState("");
  const [parentId, setParentId] = useState("");
  const [areaPath, setAreaPath] = useState("");
  const [iterationPath, setIterationPath] = useState("");
  const [countryValue, setCountryValue] = useState("");
  const [tags, setTags] = useState("");
  const [description, setDescription] = useState("");
  const flat = flattenWithDepth(items);

  function submit(event) {
    event.preventDefault();
    if (!title.trim()) return;
    onAdd({
      id: `manual-${Date.now()}`,
      parentId: parentId || null,
      type,
      title: title.trim(),
      areaPath: areaPath.trim(),
      iterationPath: iterationPath.trim(),
      countryValue: countryValue.trim(),
      tags: tags.trim(),
      description: description.trim()
    });
    setTitle("");
    setDescription("");
  }

  return (
    <form data-allow-submit="true" className="mbwi-manual-form" onSubmit={submit}>
      <div className="mbw-form-grid">
        <label className="mbw-field"><span>Tipo</span><select value={type} onChange={(event) => setType(event.target.value)}>{manualTypeOptions.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>
        <label className="mbw-field"><span>Item pai</span>
          <select value={parentId} onChange={(event) => setParentId(event.target.value)}>
            <option value="">Nenhum (raiz)</option>
            {flat.map((item) => <option key={item.id} value={item.id}>{"— ".repeat(item.depth)}{item.type}: {item.title}</option>)}
          </select>
        </label>
        <TextField label="Titulo" value={title} onChange={setTitle} placeholder="Ex.: Checkout journey" />
        <TextField label="Area Path" value={areaPath} onChange={setAreaPath} placeholder="WebApp\MB Labs" />
        <TextField label="Iteration Path" value={iterationPath} onChange={setIterationPath} placeholder="WebApp\MB Labs\Sprint atual" />
        <TextField label="Country" value={countryValue} onChange={setCountryValue} placeholder="All, BR, AR..." />
        <TextField label="Tags" value={tags} onChange={setTags} placeholder="automation;qa" />
        <label className="mbw-field mb-span-2"><span>Description</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} placeholder="Descricao ou Steps/Expected Result para Test Case" /></label>
      </div>
      <Button type="submit" tone="primary">+ Adicionar item</Button>
    </form>
  );
}

export function ImportWorkbench() {
  const { profile, demoMode } = useAuth();
  const { getSetting } = useAppSettings();
  const { runImport, importing, result } = useHierarchyImport();
  const fileRef = useRef(null);
  const defaults = getSetting("importDefaults", {});
  const [tab, setTab] = useState("manual");
  const [raw, setRaw] = useState("");
  const [manualItems, setManualItems] = useState([]);
  const [tree, setTree] = useState(null);
  const [manualDraft, setManualDraft] = useState({ type: "Epic", title: "", tags: [], tagInput: "", description: "", parentId: "" });
  const [manualEditItemId, setManualEditItemId] = useState(null);
  const [showManualModal, setShowManualModal] = useState(false);
  const [showWizard, setShowWizard] = useState(false);
  const [draggingId, setDraggingId] = useState(null);
  const [dropTargetId, setDropTargetId] = useState(null);
  const [dragOverRoot, setDragOverRoot] = useState(false);
  const [expandedNodeIds, setExpandedNodeIds] = useState(new Set());
  const [areaPath, setAreaPath] = useState(profile?.azureTeam ? `${profile.azureProject}\\${profile.azureTeam}` : defaults.areaPath || "");
  const [iterationPath, setIterationPath] = useState(defaults.iterationPath || profile?.azureProject || "");
  const [countryField, setCountryField] = useState(getSetting("azureCountryField", ""));
  const [log, setLog] = useState([]);
  const [progress, setProgress] = useState(0);
  const counts = tree ? countNodes(tree) : {};
  const validationErrors = tree ? validateTree(tree) : {};

  useEffect(() => {
    if (!importing) return undefined;
    setProgress(6);
    const interval = setInterval(() => {
      setProgress((current) => (current < 90 ? current + Math.random() * 9 : current));
    }, 320);
    return () => clearInterval(interval);
  }, [importing]);
  useEffect(() => {
    if (result) setProgress(100);
  }, [result]);

  const parseTimer = useRef(null);
  useEffect(() => {
    if (!raw) return undefined;
    if (!looksLikeCsv(raw)) return undefined;
    clearTimeout(parseTimer.current);
    parseTimer.current = setTimeout(() => {
      parseInput(raw);
    }, 600);
    return () => clearTimeout(parseTimer.current);
  }, [raw]);
  useEffect(() => {
    if (tab === "manual") {
      setTreeWithIds(buildTreeFromManualItems(manualItems));
    }
  }, [manualItems, tab]);

  function append(message, kind = "info") {
    setLog((current) => [...current.slice(-30), { message, kind }]);
  }

  function updateManualDraft(updates) {
    setManualDraft((current) => ({ ...current, ...updates }));
  }

  function openManualModal({ type = manualDraft.type, parentId = "", itemId = null }) {
    const existing = itemId ? manualItems.find((item) => item.id === itemId) : null;
    setManualDraft({
      type,
      title: existing?.title || "",
      tags: existing?.tags ? String(existing.tags).split(";").map((tag) => tag.trim()).filter(Boolean) : [],
      tagInput: "",
      description: existing?.description || "",
      parentId: existing?.parentId || parentId || ""
    });
    setManualEditItemId(itemId);
    setShowManualModal(true);
  }

  function clearManualModal() {
    setManualEditItemId(null);
    setManualDraft({ type: "Epic", title: "", tags: [], tagInput: "", description: "", parentId: "" });
    setShowManualModal(false);
  }

  function handleManualTagAdd(value) {
    const normalized = normalizeTag(value);
    if (!normalized) return;
    if (manualDraft.tags.includes(normalized)) return;
    updateManualDraft({ tags: [...manualDraft.tags, normalized], tagInput: "" });
  }

  function handleManualTagRemove(tag) {
    updateManualDraft({ tags: manualDraft.tags.filter((current) => current !== tag) });
  }

  function saveManualDraft() {
    const title = manualDraft.title.trim();
    if (!title) {
      append("Titulo é obrigatório para o item manual.", "error");
      return;
    }
    const tags = manualDraft.tags.map((tag) => normalizeTag(tag)).filter(Boolean);
    const nextItem = {
      id: manualEditItemId || `manual-${Date.now()}`,
      parentId: manualDraft.parentId || null,
      type: manualDraft.type,
      title,
      areaPath: areaPath,
      iterationPath: iterationPath,
      countryValue: countryField || "",
      tags: tags.join(";"),
      description: manualDraft.description.trim()
    };

    setManualItems((current) => {
      if (manualEditItemId) {
        return current.map((item) => (item.id === manualEditItemId ? nextItem : item));
      }
      return [...current, nextItem];
    });
    clearManualModal();
    append(`${nextItem.type} adicionado à prévia manual.`, "success");
  }

  function setTreeWithIds(nextTree) {
    const treeCopy = assignTreeIds(cloneTree(nextTree));
    setTree(treeCopy);
    setExpandedNodeIds(new Set(collectAllNodeIds(treeCopy)));
  }

  function parseInput(value = raw) {
    if (!looksLikeCsv(value)) {
      append('Formato nao reconhecido. Cabecalho esperado: "Work Item Type".', "error");
      return;
    }
    const nextTree = buildTreeFromCsvRows(csvRowsToObjects(parseCsv(value)));
    const source = findFirstConfigSource(nextTree);
    if (source?.opts.areaPath) setAreaPath(source.opts.areaPath);
    if (source?.opts.iterationPath) setIterationPath(source.opts.iterationPath);
    setTreeWithIds(nextTree);
    setTab("preview");
    append(`Parsed ${Object.values(countNodes(nextTree)).reduce((a, b) => a + b, 0)} work items.`, "success");
  }

  function loadDefaultCsv() {
    const csv = buildDefaultQaCsv(defaults);
    setRaw(csv);
    parseInput(csv);
  }

  function loadDefaultManual() {
    setManualItems(buildDefaultManualItems(defaults));
  }

  function addManualItem(item) {
    setManualItems((current) => [...current, item]);
  }

  function removeManualItem(id) {
    setManualItems((current) => {
      const toRemove = new Set([id]);
      let changed = true;
      while (changed) {
        changed = false;
        current.forEach((item) => {
          if (item.parentId && toRemove.has(item.parentId) && !toRemove.has(item.id)) {
            toRemove.add(item.id);
            changed = true;
          }
        });
      }
      return current.filter((item) => !toRemove.has(item.id));
    });
  }

  function moveTreeNode(sourceId, targetParentId) {
    if (!tree || sourceId === targetParentId) return;
    if (targetParentId && isAncestorOf(tree, sourceId, targetParentId)) {
      append("Nao e possivel mover um item para dentro de seu proprio descendente.", "error");
      return;
    }

    const [nextTree, removed] = removeNodeById(tree, sourceId);
    if (!removed) return;

    const updatedTree = cloneTree(nextTree);
    if (targetParentId) {
      const parent = findNodeById(updatedTree, targetParentId);
      if (!parent) return;
      parent.children = [...(parent.children || []), removed];
      setExpandedNodeIds((current) => new Set(current).add(parent.id));
    } else {
      updatedTree.children = [...(updatedTree.children || []), removed];
    }

    setTree(updatedTree);
  }

  function openNewManualItem(type, parentId = "") {
    openManualModal({ type, parentId, itemId: null });
    if (tab !== "manual") setTab("manual");
  }

  function useManualHierarchy() {
    if (!manualItems.length) {
      append("Adicione ao menos um item na hierarquia manual.", "error");
      return;
    }
    const nextTree = buildTreeFromManualItems(manualItems);
    const source = findFirstConfigSource(nextTree);
    if (source?.opts.areaPath) setAreaPath(source.opts.areaPath);
    if (source?.opts.iterationPath) setIterationPath(source.opts.iterationPath);
    setTreeWithIds(nextTree);
    setTab("preview");
    append(`${manualItems.length} work item(s) prontos para revisao.`, "success");
  }

  async function handleFile(event) {
    const file = event.target.files?.[0];
    if (!file) return;
    const text = await file.text();
    setRaw(text);
    setTab("csv");
  }

  function toggleNodeExpanded(nodeId) {
    setExpandedNodeIds((current) => {
      const next = new Set(current);
      if (next.has(nodeId)) next.delete(nodeId);
      else next.add(nodeId);
      return next;
    });
  }

  function expandAll() {
    if (!tree) return;
    setExpandedNodeIds(new Set(collectAllNodeIds(tree)));
  }

  function collapseAll() {
    setExpandedNodeIds(new Set());
  }

  async function executeImport() {
    if (!tree || demoMode) return;
    append("Executando importacao...", "info");
    const outcome = await runImport(tree, { areaPath, iterationPath, countryField: countryField || undefined });
    append(outcome.ok ? "Importacao concluida." : "Importacao falhou.", outcome.ok ? "success" : "error");
  }

  const manualFlat = flattenWithDepth(manualItems);
  const exportRows = tree ? flattenTree(tree) : manualFlat;

  function exportImportCsv() {
    downloadCsv(`import-work-items-${dateStamp()}.csv`, ["Nivel", "Tipo", "Titulo", "Area Path", "Iteration Path", "Pais", "Tags", "Descricao"], exportRows.map((item) => [
      item.depth,
      item.type,
      item.title,
      item.areaPath || areaPath,
      item.iterationPath || iterationPath,
      item.countryValue || item.country || "",
      item.tags || "",
      item.description || ""
    ]));
  }

  return (
    <section className="mbw-page mbwi-page">
      <WorkbenchHeader
        kicker="Modulo 5"
        title="Import Work Items"
        subtitle="Monte a hierarquia manualmente ou cole um CSV, revise a previa e importe."
        demoMode={demoMode}
        actions={<Button tone="primary" onClick={() => setShowWizard(true)}><i className="bi bi-magic" /> Criar Work Item</Button>}
      />
      {showWizard && <CreateWorkItemWizard onClose={() => setShowWizard(false)} />}
      <input ref={fileRef} type="file" hidden accept=".csv,.tsv,.txt" onChange={handleFile} />
      <div className="mbwi-drawer-react">
        <nav className="mbwi-tabs-react">
          {["manual", "csv", "logs"].map((value) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{{ manual: "Manual", csv: "CSV", logs: "Logs" }[value]}</button>)}
          <span className="mbwi-tabs-spacer" />
          {tab !== "logs" && (
            <Button onClick={() => (tab === "manual" ? loadDefaultManual() : loadDefaultCsv())}>Exemplo</Button>
          )}
        </nav>
        <div className="mbwi-body-react">
          {tab === "manual" && (
            <div className="mbwi-grid-react">
              <section className="mbwi-card-react">
                <h3>Manual <InfoTooltip text="Clique num tipo para abrir o editor, informe o título, tags e descrição e depois confirme. Arraste o tipo para a prévia para criar com pai direto." /></h3>
                <div className="mbw-form-grid mbwi-shared-settings">
                  <TextField label="Area Path" value={areaPath} onChange={setAreaPath} />
                  <TextField label="Iteration Path" value={iterationPath} onChange={setIterationPath} />
                  <TextField label="Country" value={countryField} onChange={setCountryField} placeholder="All, BR, AR..." />
                </div>
                <div className="mbwi-type-pills">
                  {manualTypeOptions.map((type) => (
                    <button
                      key={type}
                      type="button"
                      className={`mbwi-type-pill ${manualDraft.type === type ? "active" : ""}`}
                      draggable
                      onDragStart={(event) => {
                        event.dataTransfer.setData("text/plain", `new-type:${type}`);
                        event.dataTransfer.effectAllowed = "copy";
                      }}
                        onClick={() => openManualModal({ type, parentId: "" })}
                    >
                      <img src={typeIconSrc(type)} alt="" className="mbwi-type-pill-icon" />
                      {type}
                    </button>
                  ))}
                </div>
              </section>
              <section className="mbwi-card-react">
                <h3>Prévia</h3>
                <div className={`mbwi-tree-preview${dragOverRoot ? " mbwi-tree-root-active" : ""}`}
                  onDragOver={(event) => {
                    event.preventDefault();
                    if (event.target === event.currentTarget) {
                      setDragOverRoot(true);
                      setDropTargetId(null);
                    }
                  }}
                  onDragLeave={() => setDragOverRoot(false)}
                  onDrop={(event) => {
                    event.preventDefault();
                    const payload = event.dataTransfer.getData("text/plain") || "";
                    if (payload.startsWith("new-type:")) {
                      openManualModal({ type: payload.replace("new-type:", ""), parentId: "" });
                      setDragOverRoot(false);
                      return;
                    }
                    if (payload) moveTreeNode(payload, null);
                    setDragOverRoot(false);
                  }}
                >
                  <div className="mbwi-tree-drop-hint">Arraste aqui para criar item na raiz ou soltar sobre outro item para torná-lo filho.</div>
                  {tree ? <TreePreview node={tree} draggingId={draggingId} dropTargetId={dropTargetId} onToggle={{ toggle: toggleNodeExpanded, setDragging: setDraggingId, clearDrag: () => { setDraggingId(null); setDropTargetId(null); }, setDropTarget: setDropTargetId, clearDropTarget: () => setDropTargetId(null), isExpanded: (id) => expandedNodeIds.has(id), onDropNewType: (type, parentId) => openManualModal({ type, parentId }), onEdit: (id) => openManualModal({ itemId: id }) }} onMove={moveTreeNode} errors={validationErrors} /> : <EmptyState title="Nenhum item criado ainda" />}
                </div>
              </section>
            </div>
          )}
          {tab === "csv" && (
            <div className="mbwi-grid-react">
              <section className="mbwi-card-react">
                <h3>CSV / TSV</h3>
                <p>Aceita ID, Work Item Type, Title 1...Title 5, Area Path, Iteration Path, Country, Tags e Description.</p>
                <textarea value={raw} onChange={(event) => setRaw(event.target.value)} placeholder="Cole o CSV/TSV aqui" />
                <div className="mbw-actions"><Button onClick={() => fileRef.current?.click()}>Carregar arquivo CSV</Button></div>
              </section>
              <section className="mbwi-card-react">
                <h3>Preview</h3>
                <div
                  className={`mbwi-tree-preview${dragOverRoot ? " mbwi-tree-root-active" : ""}`}
                  onDragOver={(event) => {
                    event.preventDefault();
                    if (event.target === event.currentTarget) {
                      setDragOverRoot(true);
                      setDropTargetId(null);
                    }
                  }}
                  onDragLeave={() => setDragOverRoot(false)}
                  onDrop={(event) => {
                    event.preventDefault();
                    const sourceId = event.dataTransfer.getData("text/plain");
                    if (sourceId) moveTreeNode(sourceId, null);
                    setDragOverRoot(false);
                  }}
                >
                  <div className="mbwi-tree-drop-hint">Arraste aqui para mover para raiz</div>
                  {tree ? <TreePreview node={tree} draggingId={draggingId} dropTargetId={dropTargetId} onToggle={{ toggle: toggleNodeExpanded, setDragging: setDraggingId, clearDrag: () => { setDraggingId(null); setDropTargetId(null); }, setDropTarget: setDropTargetId, clearDropTarget: () => setDropTargetId(null), isExpanded: (id) => expandedNodeIds.has(id) }} onMove={moveTreeNode} /> : <EmptyState title="Nenhum item carregado" />}
                </div>
              </section>
            </div>
          )}
          {tab === "logs" && (
            <section className="mbwi-card-react">
              <h3>Logs</h3>
              {log.length > 0
                ? <div className="mbwi-log-react">{log.map((entry, index) => <div key={index} className={entry.kind}>{entry.message}</div>)}</div>
                : <EmptyState title="Nenhum log ainda" />}
            </section>
          )}
        </div>
        <footer className="mbwi-footer-react">
          <span className="mbwi-spacer" />
          <Button disabled={!tree || demoMode || importing} onClick={executeImport} tone="primary">{importing ? "Importando..." : "Executar importacao"}</Button>
          {demoMode && <span className="mbw-muted">Import real indisponivel no modo demo.</span>}
        </footer>
        {(importing || result) && (
          <div className="mbwi-progress-wrap">
            <div className="mbwi-progress-bar"><b style={{ width: `${progress}%` }} className={result && !result.ok ? "error" : ""} /></div>
            <span>{importing ? `Importando... ${Math.round(progress)}%` : result?.ok ? "Concluido" : "Falhou"}</span>
          </div>
        )}
      </div>
      {showManualModal && (
        <div className="mbwi-modal-backdrop" onMouseDown={() => setShowManualModal(false)}>
          <div className="mbwi-modal" onMouseDown={(e) => e.stopPropagation()}>
            <h3>{manualEditItemId ? "Editar item" : "Criar item"}</h3>
            <div className="mbw-form-grid">
              <label className="mbw-field"><span>Tipo</span><input readOnly value={manualDraft.type} /></label>
              <label className="mbw-field"><span>Pai</span>
                <select value={manualDraft.parentId} onChange={(event) => updateManualDraft({ parentId: event.target.value })}>
                  <option value="">Raiz</option>
                  {manualItems.map((item) => (
                    <option key={item.id} value={item.id}>{item.type}: {item.title}</option>
                  ))}
                </select>
              </label>
              <TextField label="Titulo" value={manualDraft.title} onChange={(value) => updateManualDraft({ title: value })} placeholder="Digite o titulo do work item" />
              <label className="mbw-field mb-span-2"><span>Tags</span><TagInput tags={manualDraft.tags} value={manualDraft.tagInput} onChange={(value) => updateManualDraft({ tagInput: value })} onAdd={handleManualTagAdd} onRemove={handleManualTagRemove} placeholder="Enter para adicionar" /></label>
              <label className="mbw-field mb-span-2"><span>Description</span><textarea value={manualDraft.description} onChange={(event) => updateManualDraft({ description: event.target.value })} rows={4} placeholder="Descricao ou Steps/Expected Result para Test Case" /></label>
            </div>
            <div className="mbw-actions">
              <Button tone="primary" onClick={saveManualDraft}>{manualEditItemId ? "Salvar" : "Confirmar"}</Button>
              {manualEditItemId && <Button onClick={() => { removeManualItem(manualEditItemId); clearManualModal(); append('Item manual removido.', 'info'); }}>Excluir</Button>}
              <Button tone="secondary" onClick={clearManualModal}>Cancelar</Button>
            </div>
          </div>
        </div>
      )}

      {result && (
        <section className="mbwi-card-react mbwi-result">
          <h3>Resumo da importacao</h3>
          {result.ok ? (
            <>
              <div className="mbw-kpi-row">{Object.entries(result.counts || {}).map(([type, count]) => <Kpi key={type} label={type} value={count} />)}</div>
              {Array.isArray(result.log) && result.log.length > 0 && <div className="mbwi-result-log">{result.log.map((line, index) => <div key={index}>{line}</div>)}</div>}
            </>
          ) : (
            <div className="mbw-alert error">{result.error}</div>
          )}
        </section>
      )}
    </section>
  );
}
