import { useEffect, useRef, useState } from "react";
import { FiUpload } from "react-icons/fi";
import { useAuth } from "../../../contexts/AuthContext.jsx";
import { useAppSettings } from "../../../hooks/useAppSettings.js";
import { useHierarchyImport } from "../../../hooks/useHierarchyImport.js";
import {
  buildTreeFromCsvRows,
  buildTreeFromManualItems,
  countNodes,
  csvRowsToObjects,
  findFirstConfigSource,
  looksLikeCsv,
  parseCsv
} from "../../../utils/hierarchyImport.js";
import { csvCell } from "../../../utils/workbench/formatters.js";
import { Button, EmptyState, Kpi, TextField, TypeBadge, WorkbenchHeader } from "../ui/WorkbenchPrimitives.jsx";

const manualTypeOptions = ["Epic", "Feature", "User Story", "Task", "Test Case", "Bug"];

function buildDefaultQaCsv(defaults = {}) {
  const area = defaults.areaPath || "WebApp\\MB Labs";
  const iteration = defaults.iterationPath || "WebApp\\MB Labs\\May [2026] MB Labs";
  const tags = defaults.tags || "automation;qa";
  const rows = [
    ["ID", "Work Item Type", "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Area Path", "Iteration Path", "Country", "Tags", "Description"],
    ["", "Epic", "QA Automation", "", "", "", "", area, iteration, "All", tags, "Automation backlog generated by Stark Hub."],
    ["", "Feature", "", "Checkout", "", "", "", area, iteration, "All", tags, "Checkout quality coverage."],
    ["", "User Story", "", "", "[Last Minute] Automation for checkout journey.", "", "", area, iteration, "All", tags, "Checkout journey."],
    ["", "Task", "", "", "", "[Last Minute] Main Flow", "", area, iteration, "All", tags, "Main flow scenarios."],
    ["", "Test Case", "", "", "", "", "[LT] Checkout displays Last Minute component", area, iteration, "All", tags, "**Steps:**\n1. Select movie and seat.\n2. Continue to Checkout.\n\n**Expected Result:** Component is displayed above payment options."]
  ];
  return rows.map((row) => row.map(csvCell).join(",")).join("\n");
}

function buildDefaultManualItems(defaults = {}) {
  const area = defaults.areaPath || "WebApp\\MB Labs";
  const iteration = defaults.iterationPath || "WebApp\\MB Labs\\May [2026] MB Labs";
  const tags = defaults.tags || "automation;qa";
  const common = { areaPath: area, iterationPath: iteration, countryValue: "All", tags };
  const epic = { id: "manual-epic", parentId: null, type: "Epic", title: "QA Automation", ...common, description: "Automation backlog generated by Stark Hub." };
  const feature = { id: "manual-feature", parentId: epic.id, type: "Feature", title: "Checkout", ...common, description: "Checkout quality coverage." };
  const story = { id: "manual-story", parentId: feature.id, type: "User Story", title: "[Last Minute] Automation for checkout journey.", ...common, description: "Checkout journey." };
  const task = { id: "manual-task", parentId: story.id, type: "Task", title: "[Last Minute] Main Flow", ...common, description: "Main flow scenarios." };
  const testCase = { id: "manual-test", parentId: task.id, type: "Test Case", title: "[LT] Checkout displays Last Minute component", ...common, description: "**Steps:**\n1. Select movie and seat.\n2. Continue to Checkout.\n\n**Expected Result:** Component is displayed above payment options." };
  return [epic, feature, story, task, testCase];
}

function flattenWithDepth(items) {
  const byParent = new Map();
  items.forEach((item) => {
    const key = item.parentId || "root";
    if (!byParent.has(key)) byParent.set(key, []);
    byParent.get(key).push(item);
  });
  const result = [];
  (function walk(parentKey, depth) {
    (byParent.get(parentKey) || []).forEach((item) => {
      result.push({ ...item, depth });
      walk(item.id, depth + 1);
    });
  })("root", 0);
  return result;
}

function TreePreview({ node }) {
  if (!node || node.type === "root") return <>{(node?.children || []).map((child, index) => <TreePreview key={index} node={child} />)}</>;
  return (
    <div className="mbwi-node-preview">
      <div><TypeBadge type={node.type} /> <strong>{node.title}</strong></div>
      {(node.children || []).length > 0 && <div className="mbwi-node-children">{node.children.map((child, index) => <TreePreview key={index} node={child} />)}</div>}
    </div>
  );
}

function ManualItemForm({ items, onAdd }) {
  const [type, setType] = useState("Epic");
  const [title, setTitle] = useState("");
  const [parentId, setParentId] = useState("");
  const [areaPath, setAreaPath] = useState("");
  const [iterationPath, setIterationPath] = useState("");
  const [countryValue, setCountryValue] = useState("");
  const [tags, setTags] = useState("");
  const [description, setDescription] = useState("");
  const flat = flattenWithDepth(items);

  function submit(event) {
    event.preventDefault();
    if (!title.trim()) return;
    onAdd({
      id: `manual-${Date.now()}`,
      parentId: parentId || null,
      type,
      title: title.trim(),
      areaPath: areaPath.trim(),
      iterationPath: iterationPath.trim(),
      countryValue: countryValue.trim(),
      tags: tags.trim(),
      description: description.trim()
    });
    setTitle("");
    setDescription("");
  }

  return (
    <form className="mbwi-manual-form" onSubmit={submit}>
      <div className="mbw-form-grid">
        <label className="mbw-field"><span>Tipo</span><select value={type} onChange={(event) => setType(event.target.value)}>{manualTypeOptions.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>
        <label className="mbw-field"><span>Item pai</span>
          <select value={parentId} onChange={(event) => setParentId(event.target.value)}>
            <option value="">Nenhum (raiz)</option>
            {flat.map((item) => <option key={item.id} value={item.id}>{"— ".repeat(item.depth)}{item.type}: {item.title}</option>)}
          </select>
        </label>
        <TextField label="Titulo" value={title} onChange={setTitle} placeholder="Ex.: Checkout journey" />
        <TextField label="Area Path" value={areaPath} onChange={setAreaPath} placeholder="WebApp\MB Labs" />
        <TextField label="Iteration Path" value={iterationPath} onChange={setIterationPath} placeholder="WebApp\MB Labs\Sprint atual" />
        <TextField label="Country" value={countryValue} onChange={setCountryValue} placeholder="All, BR, AR..." />
        <TextField label="Tags" value={tags} onChange={setTags} placeholder="automation;qa" />
        <label className="mbw-field mb-span-2"><span>Description</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} placeholder="Descricao ou Steps/Expected Result para Test Case" /></label>
      </div>
      <Button type="submit" tone="primary">+ Adicionar item</Button>
    </form>
  );
}

export function ImportWorkbench() {
  const { profile, demoMode } = useAuth();
  const { getSetting } = useAppSettings();
  const { runImport, importing, result } = useHierarchyImport();
  const fileRef = useRef(null);
  const defaults = getSetting("importDefaults", {});
  const [tab, setTab] = useState("manual");
  const [raw, setRaw] = useState("");
  const [manualItems, setManualItems] = useState([]);
  const [tree, setTree] = useState(null);
  const [areaPath, setAreaPath] = useState(profile?.azureTeam ? `${profile.azureProject}\\${profile.azureTeam}` : defaults.areaPath || "");
  const [iterationPath, setIterationPath] = useState(defaults.iterationPath || profile?.azureProject || "");
  const [countryField, setCountryField] = useState(getSetting("azureCountryField", ""));
  const [log, setLog] = useState([]);
  const [progress, setProgress] = useState(0);
  const counts = tree ? countNodes(tree) : {};

  useEffect(() => {
    if (!importing) return undefined;
    setProgress(6);
    const interval = setInterval(() => {
      setProgress((current) => (current < 90 ? current + Math.random() * 9 : current));
    }, 320);
    return () => clearInterval(interval);
  }, [importing]);
  useEffect(() => {
    if (result) setProgress(100);
  }, [result]);

  function append(message, kind = "info") {
    setLog((current) => [...current.slice(-30), { message, kind }]);
  }

  function parseInput(value = raw) {
    if (!looksLikeCsv(value)) {
      append('Formato nao reconhecido. Cabecalho esperado: "Work Item Type".', "error");
      return;
    }
    const nextTree = buildTreeFromCsvRows(csvRowsToObjects(parseCsv(value)));
    const source = findFirstConfigSource(nextTree);
    if (source?.opts.areaPath) setAreaPath(source.opts.areaPath);
    if (source?.opts.iterationPath) setIterationPath(source.opts.iterationPath);
    setTree(nextTree);
    setTab("preview");
    append(`Parsed ${Object.values(countNodes(nextTree)).reduce((a, b) => a + b, 0)} work items.`, "success");
  }

  function loadDefaultCsv() {
    const csv = buildDefaultQaCsv(defaults);
    setRaw(csv);
    parseInput(csv);
  }

  function loadDefaultManual() {
    setManualItems(buildDefaultManualItems(defaults));
  }

  function addManualItem(item) {
    setManualItems((current) => [...current, item]);
  }

  function removeManualItem(id) {
    setManualItems((current) => {
      const toRemove = new Set([id]);
      let changed = true;
      while (changed) {
        changed = false;
        current.forEach((item) => {
          if (item.parentId && toRemove.has(item.parentId) && !toRemove.has(item.id)) {
            toRemove.add(item.id);
            changed = true;
          }
        });
      }
      return current.filter((item) => !toRemove.has(item.id));
    });
  }

  function useManualHierarchy() {
    if (!manualItems.length) {
      append("Adicione ao menos um item na hierarquia manual.", "error");
      return;
    }
    const nextTree = buildTreeFromManualItems(manualItems);
    const source = findFirstConfigSource(nextTree);
    if (source?.opts.areaPath) setAreaPath(source.opts.areaPath);
    if (source?.opts.iterationPath) setIterationPath(source.opts.iterationPath);
    setTree(nextTree);
    setTab("preview");
    append(`${manualItems.length} work item(s) prontos para revisao.`, "success");
  }

  async function handleFile(event) {
    const file = event.target.files?.[0];
    if (!file) return;
    const text = await file.text();
    setRaw(text);
    setTab("csv");
  }

  async function executeImport() {
    if (!tree || demoMode) return;
    append("Executando importacao...", "info");
    const outcome = await runImport(tree, { areaPath, iterationPath, countryField: countryField || undefined });
    append(outcome.ok ? "Importacao concluida." : "Importacao falhou.", outcome.ok ? "success" : "error");
  }

  const manualFlat = flattenWithDepth(manualItems);

  return (
    <section className="mbw-page mbwi-page">
      <WorkbenchHeader
        kicker="Modulo 5"
        title="Import Work Items"
        subtitle="Monte a hierarquia manualmente ou cole um CSV, revise a previa e importe."
        demoMode={demoMode}
        actions={<Button onClick={() => fileRef.current?.click()}><FiUpload /> Carregar arquivo CSV</Button>}
      />
      <input ref={fileRef} type="file" hidden accept=".csv,.tsv,.txt" onChange={handleFile} />
      <div className="mbwi-drawer-react">
        <nav className="mbwi-tabs-react">
          {["manual", "csv", "preview"].map((value) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{{ manual: "Manual", csv: "CSV", preview: "Previa" }[value]}</button>)}
        </nav>
        <div className="mbwi-body-react">
          {tab === "manual" && (
            <div className="mbwi-grid-react">
              <section className="mbwi-card-react">
                <h3>Adicionar item</h3>
                <p>Monte a hierarquia (Epic {'>'} Feature {'>'} User Story {'>'} Task {'>'} Test Case) item por item.</p>
                <ManualItemForm items={manualItems} onAdd={addManualItem} />
                <div className="mbw-actions"><Button onClick={loadDefaultManual}>Exemplo QA</Button></div>
              </section>
              <section className="mbwi-card-react">
                <h3>Hierarquia montada</h3>
                <div className="mbwi-manual-list">
                  {manualFlat.map((item) => (
                    <div key={item.id} className="mbwi-manual-item" style={{ paddingLeft: item.depth * 18 }}>
                      <TypeBadge type={item.type} /><span>{item.title}</span>
                      <button type="button" onClick={() => removeManualItem(item.id)} title="Remover"><i className="bi bi-x" /></button>
                    </div>
                  ))}
                  {!manualFlat.length && <EmptyState title="Nenhum item adicionado ainda" />}
                </div>
                {Boolean(manualItems.length) && <Button tone="primary" onClick={useManualHierarchy}>Usar esta hierarquia</Button>}
              </section>
            </div>
          )}
          {tab === "csv" && (
            <div className="mbwi-grid-react">
              <section className="mbwi-card-react">
                <h3>CSV / TSV</h3>
                <p>Aceita ID, Work Item Type, Title 1...Title 5, Area Path, Iteration Path, Country, Tags e Description.</p>
                <textarea value={raw} onChange={(event) => setRaw(event.target.value)} placeholder="Cole o CSV/TSV aqui" />
                <div className="mbw-actions"><Button tone="primary" onClick={() => parseInput()}>Parse CSV</Button><Button onClick={loadDefaultCsv}>Exemplo QA</Button></div>
              </section>
              <section className="mbwi-card-react"><h3>Preview</h3>{tree ? <TreePreview node={tree} /> : <EmptyState title="Nenhum item carregado" />}</section>
            </div>
          )}
          {tab === "preview" && (
            <section className="mbwi-card-react">
              <div className="mbw-form-grid">
                <TextField label="Area Path" value={areaPath} onChange={setAreaPath} />
                <TextField label="Iteration Path" value={iterationPath} onChange={setIterationPath} />
                <TextField label="Country field" value={countryField} onChange={setCountryField} placeholder="Custom.Country" />
              </div>
              <div className="mbw-kpi-row">{Object.entries(counts).map(([type, count]) => <Kpi key={type} label={type} value={count} />)}</div>
              <div className="mbwi-tree-preview">{tree ? <TreePreview node={tree} /> : <EmptyState title="Nenhuma previa gerada. Monte a hierarquia manual ou cole um CSV." />}</div>
            </section>
          )}
        </div>
        <footer className="mbwi-footer-react">
          <Button onClick={() => parseInput()} disabled={tab !== "csv"}>Validar CSV</Button>
          <Button disabled={!tree || demoMode || importing} onClick={executeImport} tone="primary">{importing ? "Importando..." : "Executar importacao"}</Button>
          <span className="mbwi-spacer" />
          {demoMode && <span className="mbw-muted">Import real indisponivel no modo demo.</span>}
        </footer>
        {(importing || result) && (
          <div className="mbwi-progress-wrap">
            <div className="mbwi-progress-bar"><b style={{ width: `${progress}%` }} className={result && !result.ok ? "error" : ""} /></div>
            <span>{importing ? `Importando... ${Math.round(progress)}%` : result?.ok ? "Concluido" : "Falhou"}</span>
          </div>
        )}
      </div>
      {log.length > 0 && (
        <div className="mbwi-log-react">
          {log.map((entry, index) => <div key={index} className={entry.kind}>{entry.message}</div>)}
        </div>
      )}
      {result && (
        <section className="mbwi-card-react mbwi-result">
          <h3>Resumo da importacao</h3>
          {result.ok ? (
            <>
              <div className="mbw-kpi-row">{Object.entries(result.counts || {}).map(([type, count]) => <Kpi key={type} label={type} value={count} />)}</div>
              {Array.isArray(result.log) && result.log.length > 0 && <div className="mbwi-result-log">{result.log.map((line, index) => <div key={index}>{line}</div>)}</div>}
            </>
          ) : (
            <div className="mbw-alert error">{result.error}</div>
          )}
        </section>
      )}
    </section>
  );
}
